// https://syzkaller.appspot.com/bug?id=9ef8c538552daecf5ee8a9314d051763ef372080
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(a1 % 10);
      a1 /= 10;
    }
    return open(buf, a2, 0);
  }
}

static long syz_open_procfs(volatile long a0, volatile long a1)
{
  char buf[128];
  memset(buf, 0, sizeof(buf));
  if (a0 == 0) {
    snprintf(buf, sizeof(buf), "/proc/self/%s", (char*)a1);
  } else if (a0 == -1) {
    snprintf(buf, sizeof(buf), "/proc/thread-self/%s", (char*)a1);
  } else {
    snprintf(buf, sizeof(buf), "/proc/self/task/%d/%s", (int)a0, (char*)a1);
  }
  int fd = open(buf, O_RDWR);
  if (fd == -1)
    fd = open(buf, O_RDONLY);
  return fd;
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000000, "/dev/input/mice\000", 16);
  syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000000ul, 0ul, 0);
  memcpy((void*)0x20000080, "./file0\000", 8);
  syscall(__NR_mkdir, 0x20000080ul, 0ul);
  memcpy((void*)0x200000c0, "fd/3\000", 5);
  res = syz_open_procfs(0, 0x200000c0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000500, "/dev/snd/pcmC#D#p\000", 18);
  res = syz_open_dev(0x20000500, 0, 0);
  if (res != -1)
    r[1] = res;
  memcpy((void*)0x200002c0, "./file0\000", 8);
  memcpy((void*)0x20000040, "9p\000", 3);
  memcpy((void*)0x20000140, "trans=fd,", 9);
  memcpy((void*)0x20000149, "rfdno", 5);
  *(uint8_t*)0x2000014e = 0x3d;
  sprintf((char*)0x2000014f, "0x%016llx", (long long)r[0]);
  *(uint8_t*)0x20000161 = 0x2c;
  memcpy((void*)0x20000162, "wfdno", 5);
  *(uint8_t*)0x20000167 = 0x3d;
  sprintf((char*)0x20000168, "0x%016llx", (long long)r[1]);
  *(uint8_t*)0x2000017a = 0x2c;
  *(uint8_t*)0x2000017b = 0;
  syscall(__NR_mount, 0ul, 0x200002c0ul, 0x20000040ul, 0ul, 0x20000140ul);
  return 0;
}


